name: "Hello World Action By Enrique Sarmiento"
description: "Greet someone and record the time"
inputs:
  ## esto es lo que iria en el with al usar el action
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node20"
  main: "index.js"
branding:
  icon: "message-square"
  color: "green"
